### ISSUE TITLE
Setting to add favourite artist

### ISSUE THREAD

**Issue by xthesaintx** [patrickkfkan/volumio-soundcloud#1]
It would be great to have an area in settings to add a list of favorite artists so they appear at the top of the soundcloud page. 

For example; add Favourite = "https://soundcloud.com/chanceswithwolves" and that would be the top tile on the soundcloud page.

**Comment by patrickkfkan** [comment]
Made mental note to implement this.

**Comment by patrickkfkan** [comment]
Closing this as v1.0.0 and above provides access to library items through an access token. This includes following artists.
