### ISSUE TITLE
html corrupt when searching for a track/album/artist/playlist

### ISSUE THREAD

**Issue by Windigo** [patrickkfkan/volumio-soundcloud#2]
When searching for a track/album/artist/playlist, the html is corrupted. As well on my phone (app) as in the browser on my computer.

Is this library still in development?!?!?

**Comment by Phylanxy** [comment]
I have the same issue :') This plugin used to enhance my volumio experience SO much! Would love to see it come alive again.

**Comment by patrickkfkan** [comment]
Fixed in v0.1.5 (currently in beta channel of Volumio plugin store)

**Comment by Windigo** [comment]
This beta version dorsn't seem to fix it on my device


Op do 15 jun. 2023 17:22 schreef Patrick Kan ***@***.***>:

**Comment by patrickkfkan** [comment]
Did you actually install the beta version as follows 

1. Enable Plugins Test Mode in `http://<your volumio/dev`
1. Uninstall current plugin
2. Restart Volumio
3. In plugin store, click "Details" under Soundcloud plugin, then "Install 0.1.5 (beta)"

**Comment by Windigo** [comment]
Yes, i did it like that. But i just uninstalled it again and installed it
via my browser on the computer and now it works.
In the Volumio app on my phone, the installation hang twice but it looked
like it was installed (correct version and all). Now via the browser it
worked...thanks for your service :-)

Op vr 16 jun 2023 om 09:27 schreef Patrick Kan ***@***.***>:
