### ISSUE TITLE
Playback casting to other devices

### ISSUE THREAD

**Issue by squadgazzz** [patrickkfkan/volumio-soundcloud#5]
The SoundCloud mobile app(and probably desktop also) has a feature that allows users to broadcast playback to another device running SoundCloud (e.g., smart speakers, other mobile devices). It would be beneficial to implement a similar feature in this plugin, like it is done for the Youtube plugin and others.

**Comment by patrickkfkan** [comment]
If you're talking about Chromecast then I don't think it is possible...

**Comment by squadgazzz** [comment]
> If you're talking about Chromecast then I don't think it is possible...

Could you elaborate on why exactly? Since it works for other devices. So, technically, it should be possible.
